<?php echo '<?php'; ?>

namespace <?php echo $this->crudGenerator->getControllerNamespace(); ?>\Controller;

use Zend\View\Model\ViewModel;
use Zend\Mvc\Controller\AbstractActionController;
use <?php echo $this->daoFactoryNamespace; ?>;
use <?php echo $this->architectGenerator->getNamespace(); ?>\<?php echo $this->ucFirstModelName; ?>FormFactory;
use <?php echo $this->dtoNamespace; ?>;

class <?php echo $this->crudGenerator->getControllerName(); ?>Controller extends AbstractActionController
{
    public function init()
    {
        if($this->_request->isXmlHttpRequest()) {
            $this->_helper->layout()->disableLayout();
        }
    }

<?php echo $this->render(__DIR__ . '/actions/', 'index.php.phtml'); ?>

<?php echo $this->render(__DIR__ . '/actions/', 'show.php.phtml'); ?>

<?php echo $this->render(__DIR__ . '/actions/', 'new.php.phtml'); ?>

<?php echo $this->render(__DIR__ . '/actions/', 'edit.php.phtml'); ?>

<?php echo $this->render(__DIR__ . '/actions/', 'delete.php.phtml'); ?>

}
