    public function deleteAction()
    {
        $<?php echo $this->modelName; ?>DAO  = <?php echo $this->daoFactoryName; ?>::getInstance($this->getServiceLocator());
        $id             = $this->params('id');

        $<?php echo $this->modelName; ?> = new <?php echo $this->dataObjectName; ?>();
        $<?php echo $this->modelName; ?>->setId($id);

        $<?php echo $this->modelName; ?>DAO->remove($<?php echo $this->modelName; ?>);

        $this->flashMessenger()->addSuccessMessage('Delete "<?php
        echo $this->crudGenerator->getDisplayName();
        ?>" with id "' . $<?php echo $this->modelName; ?>->getId() . '" done');

        return $this->redirect()->toRoute('<?php echo $this->homeRoute; ?>');
    }
