    public function editAction()
    {
        $sm = $this->getServiceLocator();
        $sm->get('viewHelperManager')->get('headTitle')->append("Update <?php echo $this->crudGenerator->getDisplayName(); ?>");

        $<?php echo $this->modelName; ?>Form = <?php echo $this->modelName; ?>FormFactory::getInstance($sm);
        $<?php echo $this->modelName; ?>DAO  = <?php echo $this->daoFactoryName; ?>::getInstance($sm);
        $datas          = $this->getRequest()->getPost()->toArray();
        $id             = $this->params('id');
        $referer        = $this->params('referer');

        $<?php echo $this->modelName; ?>DataObject = new <?php echo $this->dataObjectName; ?>();
        $<?php echo $this->modelName; ?>DataObject->setId($id);

        $<?php echo $this->modelName; ?>DataObject = $<?php echo $this->modelName; ?>DAO->find($<?php echo $this->modelName; ?>DataObject);

        if ($this->getRequest()->isGet()) {

            $<?php echo $this->modelName; ?>Form->populate($<?php echo $this->modelName; ?>DataObject);

        } elseif($this->getRequest()->isPost() && $<?php echo $this->modelName; ?>Form->isValid($datas)) {

            $<?php echo $this->modelName; ?> = $<?php echo $this->modelName; ?>Form->getDto()->setId($id);

            $<?php echo $this->modelName; ?>DAO->update($<?php echo $this->modelName; ?>);

            $this->flashMessenger()->addSuccessMessage('Update "<?php
            echo $this->crudGenerator->getDisplayName();
            ?>" with id "' . $<?php echo $this->modelName; ?>->getId() . '" successfully done');

            return $this->redirect()->toRoute('<?php echo $this->homeRoute; ?>');
        }

        return new ViewModel(array(
            '<?php echo $this->modelName; ?>'    => $<?php echo $this->modelName; ?>DataObject,
            'form'          => $<?php echo $this->modelName; ?>Form
        ));
    }
