    public function indexAction()
    {
        $serviceManager = $this->getServiceLocator();

        $serviceManager->get('viewHelperManager')->get('headTitle')->append("<?php echo ucfirst($this->crudGenerator->getDisplayNames()); ?> list");

        $<?php echo $this->modelName; ?>DAO = <?php echo $this->daoFactoryName; ?>::getInstance($serviceManager);

        return new ViewModel(array(
            'list<?php echo $this->ucFirstmodelName; ?>s' => $<?php echo $this->modelName; ?>DAO->findAll(),
            'successMessages' => $this->flashMessenger()->getCurrentSuccessMessages(),
        ));
    }
