    public function newAction()
    {
        $sm = $this->getServiceLocator();
        $sm->get('viewHelperManager')->get('headTitle')->append("Create <?php echo $this->crudGenerator->getDisplayName(); ?>");

        $<?php echo $this->modelName; ?>Form = <?php echo $this->ucFirstModelName; ?>FormFactory::getInstance($sm);
        $<?php echo $this->modelName; ?>DAO  = <?php echo $this->daoFactoryName; ?>::getInstance($sm);
        $datas          = $this->getRequest()->getPost()->toArray();

        if($this->getRequest()->isPost() && $<?php echo $this->modelName; ?>Form->isValid($datas)) {
            $<?php echo $this->modelName; ?>DAO->persist($<?php echo $this->modelName; ?>Form->getDto());

            $this->flashMessenger()->addSuccessMessage('"<?php
            echo ucfirst($this->crudGenerator->getDisplayName());
            ?>" successfully created');

            return $this->redirect()->toRoute('<?php echo $this->homeRoute; ?>');
        }

        return new ViewModel(array(
            'form' => $<?php echo $this->modelName; ?>Form
        ));
    }
