    public function deleteAction()
    {
        $<?php echo $this->dataObject->getEntityName(); ?>DAO  = <?php echo $this->dataObject->getEntityName(); ?>DAOFactory::getInstance($this->getServiceLocator());
        $id             = $this->params('id');

        $<?php echo $this->dataObject->getEntityName(); ?> = new <?php echo $this->dataObject->getEntityName(); ?>DataObject();
        $<?php echo $this->dataObject->getEntityName(); ?>->setId($id);

        $<?php echo $this->dataObject->getEntityName(); ?>DAO->remove($<?php echo $this->dataObject->getEntityName(); ?>);

        $this->flashMessenger()->addMessage('<?php echo $this->dataObject->getEntityName(); ?> supprimé');

        return $this->redirect()->toRoute('<?php echo $this->dataObject->getEntityName(); ?>');
    }