    public function deleteAction()
    {
        $id          = $this->getRequest()->getParam('id');
        $dao         = DAOFactory::getInstance();
        $formBuilder = <?php echo $this->entity_class; ?>FormBuilderFactory::getInstance();
        $dataObject  = new <?php echo $this->entity_class; ?>DataObject();
        $formData    = $this->getRequest()->getParams();

        $dataObject->setId($id);
        $dataObject = $dao->findByDataObjectId($dataObject);
        $form       = $formBuilder->getDeleteForm($dataObject);

        if($this->getRequest()->isPost() && $form->isValid($formData)) {
            $dataObject = $form->getDataObject();
            $dataObject->setId($id);

            $dao->remove($dataObject);

            if($this->_request->isXmlHttpRequest()) {
                $this->_helper->json(array('redirector' => "<?php echo $this->dataObject->getModulesName(); ?>-<?php echo $this->dataObject->getClassName(); ?>"));
            } else {
                $this->_helper->getHelper('Redirector')->goToRoute("<?php echo $this->dataObject->getModulesName(); ?>-<?php echo $this->dataObject->getClassName(); ?>");
            }
        }

        $this->view->form       = $form;
        $this->view->dataobject = $dataobject;
    }