    public function deleteAction()
    {
        $<?php echo $this->entityName; ?>DAO  = <?php echo $this->daoFactoryName; ?>::getInstance($this->getServiceLocator());
        $id             = $this->params('id');

        $<?php echo $this->entityName; ?> = new <?php echo $this->dataObjectName; ?>();
        $<?php echo $this->entityName; ?>->setId($id);

        $<?php echo $this->entityName; ?>DAO->remove($<?php echo $this->entityName; ?>);

        $this->flashMessenger()->addMessage('<?php echo $this->dataObject->getDisplayName(); ?> supprimé');

        return $this->redirect()->toRoute('<?php echo $this->homeRoute; ?>');
    }
