    public function editAction()
    {
        $sm = $this->getServiceLocator();
        $headTitle = $sm->get('viewHelperManager')->get('headTitle');
        $headTitle->append("update <?php echo $this->dataObject->getEntityName(); ?>");

        $<?php echo $this->dataObject->getEntityName(); ?>Form = <?php echo $this->dataObject->getEntityName(); ?>FormFactory::getInstance($sm);
        $<?php echo $this->dataObject->getEntityName(); ?>DAO  = <?php echo $this->dataObject->getEntityName(); ?>DAOFactory::getInstance($sm);
        $datas          = $this->getRequest()->getPost()->toArray();
        $id             = $this->params('id');
        $referer        = $this->params('referer');

        $<?php echo $this->dataObject->getEntityName(); ?>DataObject = new <?php echo $this->dataObject->getEntityName(); ?>DataObject();
        $<?php echo $this->dataObject->getEntityName(); ?>DataObject->setId($id);

        $<?php echo $this->dataObject->getEntityName(); ?>DataObject = $<?php echo $this->dataObject->getEntityName(); ?>DAO->retrieve($<?php echo $this->dataObject->getEntityName(); ?>DataObject);

        if (!$this->getRequest()->isPost()) {

            $<?php echo $this->dataObject->getEntityName(); ?>Form->populate($<?php echo $this->dataObject->getEntityName(); ?>DataObject);

        } elseif($this->getRequest()->isPost() && $<?php echo $this->dataObject->getEntityName(); ?>Form->isValid($datas)) {

            $<?php echo $this->dataObject->getEntityName(); ?> = $<?php echo $this->dataObject->getEntityName(); ?>Form->getDTO();

            $<?php echo $this->dataObject->getEntityName(); ?>->setId($id);

            $<?php echo $this->dataObject->getEntityName(); ?>DAO->update($<?php echo $this->dataObject->getEntityName(); ?>);

            $this->flashMessenger()->addMessage('Validation effectuée');

            return $this->redirect()->toRoute('<?php echo $this->dataObject->getEntityName(); ?>');
        }

        return new ViewModel(array(
            '<?php echo $this->dataObject->getEntityName(); ?>'    => $<?php echo $this->dataObject->getEntityName(); ?>DataObject,
            'form'          => $<?php echo $this->dataObject->getEntityName(); ?>Form,
            'flashMessages' => $this->flashMessenger()->getMessages()
        ));
    }