    public function editAction()
    {
        if($this->_request->isXmlHttpRequest()) {
            $this->_helper->layout()->disableLayout();
            $this->_helper->viewRenderer->setRender('edit-js'); 
        }
 
        $formBuilder = <?php echo $this->entity_class; ?>FormBuilderFactory::getInstance();
        $dao         = DAOFactory::getInstance();
        $id          = $this->getRequest()->getParam('id');
        $dataObject  = new <?php echo $this->entity_class; ?>DataObject();

        $dataObject->setId($id);

        $dataObject = $dao->find($dataObject);

        $formData = $this->getRequest()->getParams();
        $form     = $formBuilder->modifyBaseForm($dataObject);

        if($this->getRequest()->isPost()) {
            $form->populate($formData);
        }

        if($this->getRequest()->isPost() && $form->isValid($formData)) {
            $dataObject = $form->getDataObject();
            $dataObject->setId($id);

            $dao->modify($dataObject);
            if($this->_request->isXmlHttpRequest()) {
                $this->_helper->json(array('redirector' => "<?php echo $this->dataObject->getModulesName(); ?>-<?php echo $this->dataObject->getClassName(); ?>"));
            } else {
                $this->_helper->getHelper('Redirector')->goToRoute("<?php echo $this->dataObject->getModulesName(); ?>-<?php echo $this->dataObject->getClassName(); ?>");
            }
        }

        $this->view->form = $form;
    }