    public function indexAction()
    {
        $sm = $this->getServiceLocator();
        $headTitle = $sm->get('viewHelperManager')->get('headTitle');
        $headTitle->append("Liste des <?php echo $this->dataObject->getEntityName(); ?>s");

        $<?php echo $this->dataObject->getEntityName(); ?>DAO = <?php echo $this->dataObject->getEntityName(); ?>DAOFactory::getInstance($sm);

        return new ViewModel(array(
            'list<?php echo $this->dataObject->getEntityName(); ?>s' => $<?php echo $this->dataObject->getEntityName(); ?>DAO->retrieveAll(),
            'flashMessages' => $this->flashMessenger()->getMessages(),
        ));
    }