<?php
echo '<?php' . "\n";
$databaseConnectorClassName     = $this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/className.phtml');
$databaseConnectionVariableName = $this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/variableName.phtml');

?>
namespace <?php echo $this->architectGenerator->getNamespace(); ?>\DAO;

use <?php echo $this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/fullClass.phtml'); ?>;
use <?php echo $this->hydratorNamespace; ?>;
use <?php echo $this->dtoNamespace; ?>;
use <?php echo $this->dtoCollectionNamespace; ?>;
use <?php echo $this->exceptionNamespace; ?>;
<?php if ('doctrine2' === $this->architectGenerator->getEnvironnement('backend')): ?>
use <?php echo $this->architectGenerator->getMetadata()->getOriginalName(); ?>;
<?php endif; ?>

class <?php echo $this->daoName . "\n"; ?>
{
    /**
     * @var <?php echo $databaseConnectorClassName . "\n"; ?>
     */
    private $<?php echo $databaseConnectionVariableName; ?> = null;
    /**
     * @var <?php echo $this->hydratorName . "\n"; ?>
     */
    private $hydrator      = null;

    /**
     * @param <?php echo $databaseConnectorClassName; ?> $<?php echo $databaseConnectionVariableName . "\n"; ?>
     * @param <?php echo $this->hydratorName; ?> $hydrator
     */
    public function __construct(<?php echo $databaseConnectorClassName; ?> $<?php echo $databaseConnectionVariableName; ?>, <?php echo $this->hydratorName; ?> $hydrator)
    {
        $this-><?php echo $databaseConnectionVariableName; ?> = $<?php echo $databaseConnectionVariableName; ?>;
        $this->hydrator = $hydrator;
    }

    /**
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->modelName . "\n"; ?>
     * @throws <?php echo $this->exceptionName . "\n"; ?>
     * @return <?php echo $this->dataObjectName . "\n"; ?>
     */
    public function find(<?php echo $this->dataObjectName; ?> $<?php echo $this->modelName; ?>)
    {
        <?php echo $this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/queryFindOneBy.phtml'); ?>

        if(empty($result)) {
            throw new <?php echo $this->exceptionName; ?>('<?php echo $this->modelName; ?> not found');
        }

        return $this->hydrator->entityToPopo(
            $result,
            new <?php echo $this->dataObjectName . "\n"; ?>
        );
    }

    /**
     * @return <?php echo $this->collectionName . "\n"; ?>
     */
    public function findAll()
    {
        <?php echo $this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/queryFindAll.phtml'); ?>

        return $this->hydrator->entityCollectionToPopoCollection(
            $results,
            new <?php echo $this->collectionName; ?>,
            new <?php echo $this->dataObjectName . "\n"; ?>
        );
    }

    /**
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->modelName . "\n"; ?>
     * @return <?php echo $this->dataObjectName . "\n"; ?>
     */
    public function persist(<?php echo $this->dataObjectName; ?> $<?php echo $this->modelName; ?>)
    {
        $result = $this->hydrator->popoToEntity(
            $<?php echo $this->modelName; ?>,
<?php if ($this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/typeReturnedByDatabase.phtml') == 'entity'): ?>
            new <?php echo $this->dataObjectName; ?>()
<?php elseif ($this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/typeReturnedByDatabase.phtml') == 'array'): ?>
            array()
<?php endif; ?>
        );

        <?php echo $this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/persistQuery.phtml'); ?>

        return $this->hydrator->entityToPopo(
            $result,
            new <?php echo $this->dataObjectName . "\n"; ?>
        );
    }

    /**
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->modelName . "\n"; ?>
     * @return <?php echo $this->dataObjectName . "\n"; ?>
     */
    public function modify(<?php echo $this->dataObjectName; ?> $<?php echo $this->modelName; ?>)
    {
        <?php echo $this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/queryFindOneBy.phtml'); ?>

        if(empty($result)) {
            throw new <?php echo $this->exceptionName; ?>('<?php echo $this->modelName; ?> not found');
        }

        $result = $this->hydrator->popoToEntity(
            $<?php echo $this->modelName; ?>,
            $result
        );

        <?php echo $this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/modifyQuery.phtml'); ?>

        return $this->hydrator->entityToPopo(
            $result,
            new <?php echo $this->dataObjectName . "\n"; ?>
        );
    }

    /**
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->modelName . "\n"; ?>
     * @throws <?php echo $this->exceptionName . "\n"; ?>
     */
    public function remove(<?php echo $this->dataObjectName; ?> $<?php echo $this->modelName; ?>)
    {
        <?php echo $this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/queryFindOneBy.phtml'); ?>

        if(empty($result)) {
            throw new <?php echo $this->exceptionName; ?>('<?php echo $this->modelName; ?> not found');
        }

        <?php echo $this->renderFile(__DIR__ . '/environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/removeQuery.phtml'); ?>
    }
}
