language: php

php:
  - 5.3

env:
  - DB=sqlite 
  - ZF2_VERSION="2.1.*" DOCTRINE2_VERSION="0.*"

before_script:
  - composer install
  - composer require zendframework/zendframework:${ZF2_VERSION}
  - composer require doctrine/doctrine-orm-module:${DOCTRINE2_VERSION}

script: phpunit --configuration "tests/phpunit.xml" tests/

notifications:
  email:
    - demonchaux.stephane@gmail.com