language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev
  - composer require satooshi/php-coveralls:dev-master --dev
  - psql -c 'DROP DATABASE IF EXISTS code_generator;' -U postgres
  - psql -c 'create database code_generator; ' -U postgres
  - psql -U postgres -d code_generator -a -f ./tests/pg-table.sql

script: 
  - mkdir -p build
  - mkdir -p build/logs
  - phpunit --configuration "tests/phpunit.xml" --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls

notifications:
  email:
    - demonchaux.stephane@gmail.com