language: php

php:
  - 5.3

env:
  - TESTSUITE=ZF2 ZF2_VERSION="2.1.*" DOCTRINE2_VERSION="0.*"

before_script:
  - composer install
  - composer require satooshi/php-coveralls:dev-master --dev
  - sh -c "if [ '$TESTSUITE' = 'ZF2' ]; then composer require zendframework/zendframework:${ZF2_VERSION} ;fi"
  - sh -c "if [ '$TESTSUITE' = 'ZF2' ]; then composer require doctrine/doctrine-orm-module:${DOCTRINE2_VERSION} ;fi"
  - sh -c "if [ '$TESTSUITE' = 'ZF2' ]; then psql -c 'DROP DATABASE IF EXISTS code_generator;' -U postgres ;fi"
  - sh -c "if [ '$TESTSUITE' = 'ZF2' ]; then psql -c 'create database code_generator; ' -U postgres ;fi"

script: 
  - mkdir -p build
  - mkdir -p build/logs
  - phpunit --configuration "tests/phpunit.xml" --process-isolation --coverage-clover build/logs/clover.xml tests/

after_script:
  - php vendor/bin/coveralls

notifications:
  email:
    - demonchaux.stephane@gmail.com