language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - alias composer="hhvm -v ResourceLimit.SocketDefaultTimeout=30 -v Http.SlowQueryThreshold=30000 -v Eval.Jit=false /usr/local/bin/composer"
  - composer self-update
  - composer install --dev
  - psql -c 'DROP DATABASE IF EXISTS code_generator;' -U postgres
  - psql -c 'create database code_generator; ' -U postgres
  - psql -U postgres -d code_generator -a -f ./tests/pg-table.sql

script: 
  - mkdir -p build
  - mkdir -p build/logs
  - phpunit --coverage-clover coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email:
    - demonchaux.stephane@gmail.com