language: php

php:
  - 5.3

env:
  - TESTSUITE=PDO DB=sqlite 
  - TESTSUITE=ZF2 ZF2_VERSION="2.1.*" DOCTRINE2_VERSION="0.*"
  - TESTSUITE=General

before_script:
  - composer install
  - sh -c "if [ '$TESTSUITE' = 'ZF2' ]; then composer require zendframework/zendframework:${ZF2_VERSION} ;fi"
  - sh -c "if [ '$TESTSUITE' = 'ZF2' ]; then composer require doctrine/doctrine-orm-module:${DOCTRINE2_VERSION} ;fi"
  - sh -c "if [ '$TESTSUITE' = 'ZF2' ]; then psql -c 'DROP DATABASE IF EXISTS code_generator_test;' -U postgres ;fi"
  - sh -c "if [ '$TESTSUITE' = 'ZF2' ]; then psql -c 'create database code_generator_test;' -U postgres ;fi"

script: phpunit --configuration "tests/phpunit.xml" --filter $TESTSUITE tests/

notifications:
  email:
    - demonchaux.stephane@gmail.com