language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install

script: phpunit --configuration "tests/phpunit.xml" tests/

notifications:
  email:
    - demonchaux.stephane@gmail.com