<?php echo '<?php' . "\n"; ?>
namespace <?php echo $this->dataObject->getNamespace(); ?>\DAO;

use Doctrine\ORM\EntityManager;
use <?php echo $this->dataObject->getNamespace(); ?>\Hydrator\<?php echo $this->dataObject->getEntityName(); ?>Hydrator;
use <?php echo $this->dataObject->getNamespace(); ?>\DataObject\<?php echo $this->dataObject->getEntityName(); ?>DataObject;
use <?php echo $this->dataObject->getNamespace(); ?>\DataObject\<?php echo $this->dataObject->getEntityName(); ?>Collection;
use <?php echo $this->dataObject->getEntity(); ?>;
use <?php echo $this->dataObject->getNamespace(); ?>\No<?php echo $this->dataObject->getEntityName(); ?>Exception;

class <?php echo $this->dataObject->getEntityName(); ?>DAO
{
    private $em           = null;
    private $hydrator     = null;

    /**
     * @param EntityManager $em
     * @param <?php echo $this->dataObject->getEntityName(); ?>Hydrator $hydrator
     */
    public function __construct(EntityManager $em, <?php echo $this->dataObject->getEntityName(); ?>Hydrator $hydrator)
    {
        $this->em           = $em;
        $this->hydrator     = $hydrator;
    }

    /**
     * @param DataObject $<?php echo $this->dataObject->getEntityName(); ?>
     * @throws No<?php echo $this->dataObject->getEntityName(); ?>Exception
     * @return <?php echo $this->dataObject->getEntityName(); ?>DataObject
     */
    public function find(<?php echo $this->dataObject->getEntityName(); ?>DataObject $<?php echo $this->dataObject->getEntityName(); ?>)
    {
        $entity = $this->em->getRepository('<?php echo $this->dataObject->getNamespace(); ?>\Doctrine\Entity\<?php echo $this->dataObject->getEntityName(); ?>')->findOneBy(array('id' => $<?php echo $this->dataObject->getEntityName(); ?>->getId()));

        if(empty($entity)) {
            throw new No<?php echo $this->dataObject->getEntityName(); ?>Exception('<?php echo $this->dataObject->getEntityName(); ?> not found');
        }

        return $this->hydrator->entityToPopo(
            $entity,
            new <?php echo $this->dataObject->getEntityName(); ?>DataObject()
        );
    }

    /**
     * @return <?php echo $this->dataObject->getEntityName(); ?>Collection
     */
    public function findAll()
    {
        $entities = $this->em->getRepository('<?php echo $this->dataObject->getNamespace(); ?>\Doctrine\Entity\<?php echo $this->dataObject->getEntityName(); ?>')->findAll();

        return $this->hydrator->entityCollectionToPopoCollection(
            $entities,
            new <?php echo $this->dataObject->getEntityName(); ?>Collection(),
            new <?php echo $this->dataObject->getEntityName(); ?>DataObject()
        );
    }

    /**
     * @param <?php echo $this->dataObject->getEntityName(); ?>DataObject $<?php echo $this->dataObject->getEntityName(); ?>
     * @return <?php echo $this->dataObject->getEntityName(); ?>DataObject
     */
    public function persist(<?php echo $this->dataObject->getEntityName(); ?>DataObject $<?php echo $this->dataObject->getEntityName(); ?>)
    {
        $entity = $this->hydrator->popoToEntity(
            $<?php echo $this->dataObject->getEntityName(); ?>,
            new <?php echo $this->dataObject->getEntityName(); ?>()
        );

        $this->em->persist($entity);
        $this->em->flush();

        return $this->hydrator->entityToPopo(
            $entity,
            new <?php echo $this->dataObject->getEntityName(); ?>DataObject()
        );
    }

    /**
     * @param <?php echo $this->dataObject->getEntityName(); ?>DataObject $<?php echo $this->dataObject->getEntityName(); ?>
     * @return <?php echo $this->dataObject->getEntityName(); ?>DataObject
     */
    public function modify(<?php echo $this->dataObject->getEntityName(); ?>DataObject $<?php echo $this->dataObject->getEntityName(); ?>)
    {
        $entity = $this->em->getRepository('<?php echo $this->dataObject->getNamespace(); ?>\Doctrine\Entity\<?php echo $this->dataObject->getEntityName(); ?>')->findOneBy(array('id' => $<?php echo $this->dataObject->getEntityName(); ?>->getId()));

        if(empty($entity)) {
            throw new No<?php echo $this->dataObject->getEntityName(); ?>Exception('<?php echo $this->dataObject->getEntityName(); ?> not found');
        }

        $entity = $this->hydrator->popoToEntity(
            $<?php echo $this->dataObject->getEntityName(); ?>,
            $entity
        );

        $this->em->persist($entity);
        $this->em->flush();

        return $this->hydrator->entityToPopo(
            $entity,
            new <?php echo $this->dataObject->getEntityName(); ?>DataObject()
        );
    }

    public function remove(<?php echo $this->dataObject->getEntityName(); ?>DataObject $<?php echo $this->dataObject->getEntityName(); ?>)
    {
        $entity = $this->em->getRepository('<?php echo $this->dataObject->getNamespace(); ?>\Doctrine\Entity\<?php echo $this->dataObject->getEntityName(); ?>')->findOneBy(array('id' => $<?php echo $this->dataObject->getEntityName(); ?>->getId()));

        if(empty($entity)) {
            throw new No<?php echo $this->dataObject->getEntityName(); ?>Exception('<?php echo $this->dataObject->getEntityName(); ?> not found');
        }

        $em->remove($entity);
        $em->flush();
    }
}