<?php
echo '<?php' . "\n";
$databaseConnectorClassName     = $this->getHelper('TemplateDatabaseConnector')->getClassName();
$databaseConnectionVariableName = $this->getHelper('TemplateDatabaseConnector')->getVariableName();

?>
namespace <?php echo $this->dataObject->getNamespace(); ?>\DAO;

use <?php echo $this->getHelper('TemplateDatabaseConnector')->getFullClass(); ?>;
use <?php echo $this->hydratorNamespace; ?>;
use <?php echo $this->dtoNamespace; ?>;
use <?php echo $this->dtoCollectionNamespace; ?>;
use <?php echo $this->exceptionNamespace; ?>;
use <?php echo $this->dataObject->getEntity(); ?>;

class <?php echo $this->daoName . "\n"; ?>
{
    /**
     * @var <?php echo $databaseConnectorClassName . "\n"; ?>
     */
    private $<?php echo $databaseConnectionVariableName; ?> = null;
    /**
     * @var <?php echo $this->hydratorName . "\n"; ?>
     */
    private $hydrator      = null;

    /**
     * @param <?php echo $databaseConnectorClassName; ?> $<?php echo $databaseConnectionVariableName . "\n"; ?>
     * @param <?php echo $this->hydratorName; ?> $hydrator
     */
    public function __construct(<?php echo $databaseConnectorClassName; ?> $<?php echo $databaseConnectionVariableName; ?>, <?php echo $this->entityName; ?>Hydrator $hydrator)
    {
        $this-><?php echo $databaseConnectionVariableName; ?> = $<?php echo $databaseConnectionVariableName; ?>;
        $this->hydrator = $hydrator;
    }

    /**
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->entityName . "\n"; ?>
     * @throws <?php echo $this->exceptionName . "\n"; ?>
     * @return <?php echo $this->dataObjectName . "\n"; ?>
     */
    public function find(<?php echo $this->dataObjectName; ?> $<?php echo $this->entityName; ?>)
    {
        <?php echo $this->getHelper('TemplateDatabaseConnector')->getQueryFindOneBy($this->dataObject) . "\n"; ?>

        if(empty($result)) {
            throw new $<?php echo $this->exceptionName; ?>('<?php echo $this->entityName; ?> not found');
        }

        return $this->hydrator->entityToPopo(
            $result,
            new <?php echo $this->dataObjectName . "\n"; ?>
        );
    }

    /**
     * @return <?php echo $this->collectionName . "\n"; ?>
     */
    public function findAll()
    {
        <?php echo $this->getHelper('TemplateDatabaseConnector')->getQueryFindAll($this->dataObject) . "\n"; ?>

        return $this->hydrator->entityCollectionToPopoCollection(
            $results,
            new <?php echo $this->collectionName; ?>,
            new <?php echo $this->dataObjectName . "\n"; ?>
        );
    }

    /**
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->entityName . "\n"; ?>
     * @return <?php echo $this->dataObjectName . "\n"; ?>
     */
    public function persist(<?php echo $this->dataObjectName; ?> $<?php echo $this->entityName; ?>)
    {
        $result = $this->hydrator->popoToEntity(
            $<?php echo $this->ucfirstEntityName; ?>,
            new <?php echo $this->entityName; ?>()
        );

        <?php echo $this->getHelper('TemplateDatabaseConnector')->getPersistQuery($this->dataObject) . "\n"; ?>

        return $this->hydrator->entityToPopo(
            $result,
            new <?php echo $this->dataObjectName . "\n"; ?>
        );
    }

    /**
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->entityName . "\n"; ?>
     * @return <?php echo $this->dataObjectName . "\n"; ?>
     */
    public function modify(<?php echo $this->dataObjectName; ?> $<?php echo $this->entityName; ?>)
    {
        <?php echo $this->getHelper('TemplateDatabaseConnector')->getQueryFindOneBy($this->dataObject) . "\n"; ?>

        if(empty($result)) {
            throw new <?php echo $this->exceptionName; ?>('<?php echo $this->entityName; ?> not found');
        }

        $result = $this->hydrator->popoToEntity(
            $<?php echo $this->ucfirstEntityName; ?>,
            $result
        );

        <?php echo $this->getHelper('TemplateDatabaseConnector')->getModifyQuery() . "\n"; ?>

        return $this->hydrator->entityToPopo(
            $result,
            new <?php echo $this->dataObjectName . "\n"; ?>
        );
    }

    /**
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->ucfirstEntityName . "\n"; ?>
     * @throws <?php echo $this->exceptionName . "\n"; ?>
     */
    public function remove(<?php echo $this->dataObjectName; ?> $<?php echo $this->entityName; ?>)
    {
        <?php echo $this->getHelper('TemplateDatabaseConnector')->getQueryFindOneBy($this->dataObject) . "\n"; ?>

        if(empty($result)) {
            throw new <?php echo $this->exceptionName; ?>('<?php echo $this->entityName; ?> not found');
        }

        <?php echo $this->getHelper('TemplateDatabaseConnector')->getRemoveQuery() . "\n"; ?>
    }
}