<?php echo '<?php' . "\n"; ?>
namespace <?php echo $this->dataObject->getNamespace(); ?>;

use <?php echo $this->dataObject->getNamespace(); ?>\DAO\<?php echo $this->dataObject->getEntityName(); ?>DAO;
use <?php echo $this->dataObject->getNamespace(); ?>\Hydrator\<?php echo $this->dataObject->getEntityName(); ?>Hydrator;
use Zend\ServiceManager\ServiceManager;

class <?php echo $this->dataObject->getEntityName(); ?>DAOFactory
{
    /**
     * @return <?php echo $this->dataObject->getNamespace(); ?>\DAO\<?php echo $this->dataObject->getEntityName(); ?>DAO
     */
    public static function getInstance(ServiceManager $serviceManager)
    {
        $entityManager = $serviceManager->get('doctrine.entitymanager.orm_default');
        $hydrator      = new <?php echo $this->dataObject->getEntityName(); ?>Hydrator();

        return new <?php echo $this->dataObject->getEntityName(); ?>DAO($entityManager, $hydrator);
    }
}