<?php echo '<?php' . "\n"; ?>
namespace <?php echo $this->dataObject->getNamespace(); ?>\DataObject;


class <?php echo $this->dataObject->getEntityName(); ?>DataObject
{
<?php foreach($this->dataObject->getMetadata()->fieldMappings as $field => $metadata): ?>
    private $<?php echo $field; ?> = null;
<?php endforeach; ?>

<?php foreach($this->dataObject->getMetadata()->fieldMappings as $field => $metadata): ?>
    public function set<?php echo ucfirst($field); ?>($value)
    {
        $this-><?php echo $field; ?> = $value;
        return $this;
    }
<?php endforeach; ?>

<?php foreach($this->dataObject->getMetadata()->fieldMappings as $field => $metadata): ?>
    public function get<?php echo ucfirst($field); ?>()
    {
        return $this-><?php echo $field; ?>;
    }
<?php endforeach; ?>
}