<?php
echo '<?php' . "\n";
$databaseConnectorClassName     = $this->getHelper('TemplateDatabaseConnector')->getClassName();
$databaseConnectionVariableName = $this->getHelper('TemplateDatabaseConnector')->getVariableName();

?>
namespace <?php echo $this->dataObject->getNamespace(); ?>\Hydrator;

use <?php echo $this->dtoNamespace; ?>;
use <?php echo $this->dtoCollectionNamespace; ?>;
use <?php echo $this->dataObject->getEntity(); ?>;

<?php
    $length = str_repeat(' ', strlen('a' . $this->entityName));
?>
class <?php echo $this->hydratorName . "\n"; ?>
{
    /**
     * @param <?php echo $this->entityName; ?> $entity
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->entityName . "\n"; ?>
     * @return <?php echo $this->dataObjectName . "\n"; ?>
     */
    public function entityToPopo(<?php echo $this->entityName; ?> $entity, <?php echo $this->entityName; ?>DataObject $<?php echo lcfirst($this->entityName); ?>)
    {
        $<?php echo $this->entityName; ?> = clone $<?php echo $this->entityName; ?>;

<?php
$columnCollection = $this->dataObject->getMetadata()->getColumnCollection();
foreach($columnCollection as $field => $metadata): ?>
<?php if($metadata == reset($columnCollection)): ?>
        $<?php echo $this->entityName; ?>->set<?php echo $metadata->getName(true); ?>($entity->get<?php echo $metadata->getName(true); ?>())<?php echo "\n"; ?>
<?php else: ?>
        <?php echo $length; ?>->set<?php echo $metadata->getName(true); ?>($entity->get<?php echo $metadata->getName(true); ?>())<?php if($metadata == end($columnCollection)): ?>;<?php endif; ?><?php echo "\n"; ?>
<?php endif; ?>
<?php endforeach; ?>

       return $<?php echo $this->entityName; ?>;
    }

    /**
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->entityName . "\n"; ?>
     * @param <?php echo $this->entityName; ?> $entity
     * @return <?php echo $this->dataObjectName . "\n"; ?>
     */
    public function popoToEntity(<?php echo $this->dataObjectName; ?> $<?php echo $this->entityName; ?>, <?php echo $this->entityName; ?> $entity)
    {
<?php
$columnCollection = $this->dataObject->getMetadata()->getColumnCollection();
foreach($columnCollection as $field => $metadata): ?>
<?php if($metadata == reset($columnCollection)) continue;  ?>
        $entity->set<?php echo $metadata->getName(true); ?>($<?php echo $this->entityName; ?>->get<?php echo $metadata->getName(true); ?>());<?php echo "\n"; ?>
<?php endforeach; ?>

       return $entity;
    }

    /**
     * @param array $entityCollection
     * @param <?php echo $this->collectionName; ?> $dataObjectCollection
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->entityName . "\n"; ?>
     * @return <?php echo $this->collectionName . "\n"; ?>
     */
    public function entityCollectionToPopoCollection(
        array $entityCollection,
        <?php echo $this->collectionName; ?> $dataObjectCollection,
        <?php echo $this->dataObjectName; ?> $<?php echo $this->entityName; ?>)
    {
        $dataObjectCollection = clone $dataObjectCollection;

        foreach($entityCollection as $entity) {
            $dataObjectCollection->append($this->entityToPopo($entity, $<?php echo lcfirst($this->entityName); ?>));
        }

        return $dataObjectCollection;
    }

    /**
     * @param <?php echo $this->dataObjectName; ?> $<?php echo $this->entityName . "\n"; ?>
     * @param array $datas
     * @return array
     */
    public function popoToArray(<?php echo $this->dataObjectName; ?> $<?php echo $this->entityName; ?>, $datas = array())
    {
<?php
$columnCollection = $this->dataObject->getMetadata()->getColumnCollection();
foreach($columnCollection as $field => $metadata): ?>
<?php if(in_array($metadata->getType(), array("date", "datetime"))): ?>
        $datas['<?php echo $metadata->getName(); ?>'] = $<?php echo $this->entityName; ?>->get<?php echo $metadata->getName(true); ?>()->format('Y-m-d');<?php echo "\n"; ?>
<?php else: ?>
        $datas['<?php echo $metadata->getName(); ?>'] = $<?php echo $this->entityName; ?>->get<?php echo $metadata->getName(true); ?>();<?php echo "\n"; ?>
<?php endif; ?>
<?php endforeach; ?>

       return $datas;
    }

    /**
     * @param array $datas
     * @param <?php echo $this->dataObjectName; ?> $dataObject
     */
    public function arrayToPopo(array $datas, <?php echo $this->dataObjectName; ?> $dataObject)
    {
        $dataObject = clone $dataObject;
<?php
$columnCollection = $this->dataObject->getMetadata()->getColumnCollection();
foreach($columnCollection as $field => $metadata): ?>
<?php if($metadata == reset($columnCollection)): ?>
        $dataObject->set<?php echo ucfirst($metadata->getName()); ?>(isset($datas['<?php echo $metadata->getName(); ?>']) ? $datas['<?php echo $metadata->getName(); ?>'] : null)<?php echo "\n"; ?>
<?php elseif(in_array($metadata->getType(), array("date", "datetime"))): ?>
                   ->set<?php echo ucfirst($metadata->getName()); ?>(new \DateTime($datas['<?php echo $metadata->getName(); ?>']))<?php if($metadata == end($columnCollection)): ?>;<?php endif; ?><?php echo "\n"; ?>
<?php else: ?>
                   ->set<?php echo ucfirst($metadata->getName()); ?>(isset($datas['<?php echo $metadata->getName(); ?>']) ? $datas['<?php echo $metadata->getName(); ?>'] : null)<?php if($metadata == end($columnCollection)): ?>;<?php endif; ?><?php echo "\n"; ?>
<?php endif; ?>
<?php endforeach; ?>

       return $dataObject;
    }
}