<h1><?php echo $this->ucfirstEntityName; ?> list</h1>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
        <?php foreach($this->dataObject->getMetadata()->getColumnCollection() as $metadata): ?>
    <th><?php echo $metadata->getName(true); ?></th>
        <?php endforeach; ?>
    <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php echo '<?php foreach($this->list' . $this->ucfirstEntityName . 's as $' . $this->entityName . '): ?>' . "\n"; ?>
        <tr>
<?php
            $fieldsCollection = $this->dataObject->getMetadata()->getColumnCollection();
            foreach($this->dataObject->getMetadata()->getColumnCollection() as $metadata):
                if($metadata == reset($fieldsCollection)): ?>
            <td><a href=""><?php echo '<?php echo $' . $this->entityName . '->get' . $metadata->getName(true) . '(); ?>'; ?></a></td>
<?php elseif(in_array($metadata->getType(), array("date", "datetime"))): ?>
            <td><?php echo '<?php echo $' . $this->entityName . '->get' . $metadata->getName(true) . '()->format(\'Y-m-d H:i:s\'); ?>'; ?></td>
<?php else: ?>
            <td><?php echo '<?php echo $' . $this->entityName . '->get' . $metadata->getName(true) . '(); ?>'; ?></td>
<?php endif;
 if($metadata == end($fieldsCollection)): ?>
            <td>
<?php echo $this->render(__DIR__ . '/others/', 'actions.phtml'); ?>
            </td>
                <?php endif; ?>
           <?php endforeach; ?>
        </tr>
    <?php echo '<?php endforeach; ?>'; ?>
    </tbody>
</table>

<ul>
    <li>
        <a href="<?php echo '<?php echo $this->url(array(), "' . $this->dataObject->getModuleName() . '-' . $this->dataObject->getEntityName() . '-new"); ?>'; ?>">
            Create a new entry
        </a>
    </li>
</ul>