<h1><?php echo $this->entity_class; ?> list</h1>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
        <?php foreach($this->fields as $field => $metadata): ?>
            <th><?php echo $metadata->getName(); ?></th>
        <?php endforeach; ?>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php echo '<?php foreach($this->entities as $entity): ?>'; ?>
        <tr>
            <?php foreach($this->fields as $field => $metadata): ?>
                <?php if($metadata == reset($this->fields) && in_array('show', $this->actions)): ?>
                    <td><a href=""><?php echo '<?php echo $entity->get' . $field . '(); ?>'; ?></a></td>
                <?php elseif(in_array($metadata->getType(), array("date", "datetime"))): ?>
                    <td><?php echo '<?php echo $entity->get' . $field . '()->format(\'Y-m-d H:i:s\'); ?>'; ?></td>
                <?php else: ?>
                    <td><?php echo '<?php echo $entity->get' . $field . '(); ?>'; ?></td>
                <?php endif; ?>
                <?php if($metadata == end($this->fields)): ?>
                    <td>
                        <?php echo $this->render('/crud/views/others/actions.phtml');  ?>
                    </td>
                <?php endif; ?>
           <?php endforeach; ?>
        </tr>
    <?php echo '<?php endforeach; ?>'; ?>
    </tbody>
</table>

<?php if(in_array('new', $this->actions)): ?>
<ul>
    <li>
        <a href="<?php echo '<?php echo $this->url(array(), "' . $this->dataObject->getModulesName() . '-' . $this->dataObject->getClassName() . '-new"); ?>'; ?>">
            Create a new entry
        </a>
    </li>
</ul>
<?php endif; ?>