<h1><?php echo $this->dataObject->getEntityName(); ?></h1>

<table class="record_properties">
    <tbody>
     <?php foreach($this->dataObject->getMetadata()->getColumnCollection() as $field => $metadata): ?>

        <tr>
            <th><?php echo $metadata->getName(); ?></th>

        <?php if(in_array($metadata->getType(), array("date", "datetime"))): ?>

            <?php echo '<?php echo $entity->get' . $field . '()->format(\'Y-m-d H:i:s\');' ?>'; ?>

        <?php else: ?>

            <td><?php echo '<?php echo $entity->get' . $field . '(); ?>'; ?></td>

        <?php endif; ?>

        </tr>

    <?php endforeach; ?>

    </tbody>
</table>
<?php
/*
{% set hide_edit, hide_delete = false, false %}
{% include 'views/others/record_actions.html.twig' %}
*/
?>