<h1><?php echo $this->entityName; ?></h1>

<table class="record_properties">
    <tbody>
<?php foreach($this->dataObject->getMetadata()->getColumnCollection() as $metadata): ?>
        <tr>
            <th><?php echo $metadata->getName(); ?></th>
<?php if(in_array($metadata->getType(), array("date", "datetime"))): ?>
            <?php echo '<?php echo $' . $this->entityName . '->get' . $metadata->getName(true) . '()->format(\'Y-m-d H:i:s\'); ?>'; ?>
<?php else: ?>
            <td><?php echo '<?php echo $' . $this->entityName . '->get' . $metadata->getName(true) . '(); ?>'; ?></td>
<?php endif; ?>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php
/*
{% set hide_edit, hide_delete = false, false %}
{% include 'views/others/record_actions.html.twig' %}
*/
?>