<?php echo '<?php' . "\n"; ?>

namespace <?php echo $this->unitTestNamespace; ?>\DAOFactory;

use <?php echo $this->dataObject->getNamespace(); ?>\<?php echo $this->daoName; ?>Factory;
use <?php echo $this->daoNamespace; ?>;
<?php echo $this->getHelper('TemplateServiceContainer')->getFullClassForUnitTest(); ?>

class GetInstanceTest extends \PHPUnit_Framework_TestCase
{
    public function testReturnType()
    {
        $this->assertInstanceOf(
            '<?php echo $this->daoNamespace; ?>',
            <?php echo $this->daoName; ?>Factory::getInstance(<?php echo $this->getHelper('TemplateServiceContainer')->getCreateInstanceForUnitTest() . "\n" ?>)
        );
    }
}
