<?php echo '<?php' . "\n"; ?>

namespace <?php echo $this->unitTestNamespace; ?>\DAOFactory;

use <?php echo $this->dataObject->getNamespace(); ?>\<?php echo $this->daoName; ?>Factory;
use <?php echo $this->daoNamespace; ?>;
use <?php echo $this->unitTestNamespace; ?>\Bootstrap;

class GetInstanceTest extends \PHPUnit_Framework_TestCase
{
    public function testReturnType()
    {
        $this->assertInstanceOf(
            '<?php echo $this->daoNamespace; ?>',
            <?php echo $this->daoName; ?>Factory::getInstance(Bootstrap::getServiceManager())
        );
    }
}

