<?php echo '<?php' . "\n"; ?>
use <?php echo $this->entity_namespace; ?>\<?php echo $this->entity_class; ?>;
<?php if(in_array('new', $this->actions) || in_array('edit', $this->actions)): ?>
use <?php echo $this->namespace; ?>\Form\<?php echo $this->entity_class; ?>Form;
<?php endif; ?>
use <?php echo $this->namespace; ?>\DAOFactory;
use <?php echo $this->namespace; ?>\<?php echo $this->entity_class; ?>FormBuilderFactory;
use <?php echo $this->namespace; ?>\DataObject\<?php echo $this->entity_class; ?>DataObject;

class <?php echo $this->entity_class; ?>Controller extends Zend_Controller_Action
{
    public function init()
    {
        if($this->_request->isXmlHttpRequest()) {
            $this->_helper->layout()->disableLayout();
        }
    }
<?php if(in_array('index', $this->actions)): ?>
<?php echo $this->render('/crud/actions/index.php');  ?>
<?php endif; ?>

<?php if(in_array('show', $this->actions)): ?>
<?php echo $this->render('/crud/actions/show.php');  ?>
<?php endif; ?>

<?php if(in_array('new', $this->actions)): ?>
<?php echo $this->render('/crud/actions/new.php');  ?>
<?php endif; ?>

<?php if(in_array('edit', $this->actions)): ?>
<?php echo $this->render('/crud/actions/edit.php');  ?>
<?php endif; ?>

<?php if(in_array('delete', $this->actions)): ?>
<?php echo $this->render('/crud/actions/delete.php');  ?>
<?php endif; ?>

}