<?php echo '<?php' . "\n"; ?>
$form = $this->form;
$form->prepare();

echo $form->openTag() . PHP_EOL;

<?php foreach($this->dataObject->getMetadata()->getColumnCollection() as $field => $metadata): ?>
echo $this->formInput($form->get('<?php echo $metadata->getName(); ?>')) . PHP_EOL;
<?php endforeach; ?>
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->formInput($form->get('csrf')) . PHP_EOL;
echo $form->closeTag() . PHP_EOL;