<?php echo '<?php' . "\n"; ?>
namespace <?php echo $this->unitTestNamespace; ?>\DAO;

use <?php echo $this->fixtureNamespace; ?>;
use <?php echo $this->hydratorNamespace; ?>;
use <?php echo $this->dtoNamespace; ?>;
use <?php echo $this->daoNamespace; ?>;

class FindAllTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var <?php echo $this->fixtureName . "\n"; ?>
     */
    private static $fixtureManager = null;

    protected static function setUpBeforeClass()
    {
        self::$fixtureManager = new <?php echo $this->fixtureName; ?>();
        self::$fixtureManager->purge();
    }

    protected static function tearDownAfterClass()
    {
        self::$fixtureManager->purge();
    }

    public function testFindAll()
    {
        $this->fixtureManager->loadFixture();

        $sUT = new <?php echo $this->daoName; ?>(
            self::$fixtureManager->getDatabaseConnection(),
            new <?php echo $this->hydratorName; ?>()
        );
        $<?php echo $this->entityName; ?>Data = $sUT->findAll();

        $this->assertEquals(1, $<?php echo $this->entityName; ?>Data->count());
        $this->assertInstanceOf(
            '<?php echo $this->dtoCollectionNamespace; ?>',
            $<?php echo $this->entityName; ?>Data
        );
    }
}

