<?php echo '<?php' . "\n"; ?>
namespace <?php echo $this->unitTestNamespace; ?>\<?php echo $this->daoName; ?>;

use <?php echo $this->fixtureFactoryNamespace; ?>;
use <?php echo $this->hydratorNamespace; ?>;
use <?php echo $this->dtoNamespace; ?>;
use <?php echo $this->daoNamespace; ?>;

class ModifyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var <?php echo $this->fixtureName . "\n"; ?>
     */
    private static $fixtureManager = null;

    public static function setUpBeforeClass()
    {
        self::$fixtureManager = <?php echo $this->fixtureFactoryName; ?>::getInstance();
    }

    protected function setUp()
    {
        self::$fixtureManager->purge();
    }

    public static function tearDownAfterClass()
    {
        self::$fixtureManager->purge();
    }

    public function testRemove()
    {
        $dtoPersisted = self::$fixtureManager->loadFixture();
        <?php
$columnCollection = $this->architectGenerator->getMetadata()->getColumnCollection(true);
foreach($columnCollection as $field => $metadata) {
    $metadataToTest = $metadata;
    break;
}
$modifiedValue = $this->getHelper('FixtureRenderer')->render($metadataToTest);
?>

        $dtoPersisted->set<?php echo $metadataToTest->getName(true); ?>(<?php echo $modifiedValue; ?>);
        $sUT = new <?php echo $this->daoName; ?>(
            self::$fixtureManager->getDatabaseConnection(),
            new <?php echo $this->hydratorName; ?>()
        );

        $dtoModified = $sUT->modify($dtoPersisted);
        $dtoTestable = $sUT->find($dtoModified);

        $this->assertEquals(<?php echo $modifiedValue; ?>, $dtoTestable->get<?php echo $metadataToTest->getName(true); ?>());
    }

    public function testModifyFailedWithoutId()
    {
        $sUT = new  <?php echo $this->daoName; ?>(
            self::$fixtureManager->getDatabaseConnection(),
            new <?php echo $this->hydratorName; ?>()
        );
        $dto = new <?php echo $this->dataObjectName; ?>();

        $this->setExpectedException('<?php echo $this->exceptionNamespace; ?>');
        $sUT->modify($dto);
    }

    public function testModifyFailedWithId()
    {
        $sUT = new  <?php echo $this->daoName; ?>(
            self::$fixtureManager->getDatabaseConnection(),
            new <?php echo $this->hydratorName; ?>()
        );
        $dto = new <?php echo $this->dataObjectName; ?>();
        $dto->setId('42');

        $this->setExpectedException('<?php echo $this->exceptionNamespace; ?>');
        $sUT->modify($dto);
    }
}
