<?php echo '<?php' . "\n"; ?>
namespace <?php echo $this->unitTestNamespace; ?>\DAO;

use <?php echo $this->fixtureNamespace; ?>;
use <?php echo $this->hydratorNamespace; ?>;
use <?php echo $this->dtoNamespace; ?>;
use <?php echo $this->daoNamespace; ?>;

class ModifyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var <?php echo $this->fixtureName . "\n"; ?>
     */
    private $fixtureManager = null;

    protected function setUpBeforeClass()
    {
        $this->fixtureManager = new <?php echo $this->fixtureName; ?>();
    }

    protected function setUp()
    {
        $this->fixtureManager->purge();
    }

    protected function tearDownAfterClass()
    {
        $this->fixtureManager->purge();
    }

    public function testRemove()
    {
        $this->fixtureManager->loadFixture();
        <?php
$columnCollection = $this->dataObject->getMetadata()->getColumnCollection(true);
foreach($columnCollection as $field => $metadata) {
    $metadataToTest = $metadata;
    break;
}
$modifiedValue = $this->getHelper('FixtureRenderer')->render($metadataToTest);
?>

        $dtoPersisted->set<?php echo $metadataToTest->getName(true); ?>(<?php echo $modifiedValue; ?>);
        $sUT = new <?php echo $this->daoName; ?>(
            $this->fixtureManager->getDatabaseConnection(),
            new <?php echo $this->hydratorName; ?>()
        );

        $dtoModified = $sUT->modify($dtoPersisted);

        $dtoTestable =  $sUT->find($dtoModified);

        $this->assertEquals(<?php echo $modifiedValue; ?>, $entity->get<?php echo $metadataToTest->getName(true); ?>());
    }

    public function testModifyFailed()
    {
        $sUT = new <?php echo $this->daoName; ?>(
            $this->fixtureManager->getDatabaseConnection(),
            new <?php echo $this->hydratorName; ?>()
        );
        $dto = new <?php echo $this->dataObjectName; ?>();

        $this->setExpectedException('<?php echo $this->exceptionNamespace; ?>');
        $sUT->modify($dto);
    }
}

