<?php echo '<?php' . "\n"; ?>
namespace <?php echo $this->unitTestNamespace; ?>\DAO;

use ApplicationTest\FixtureManager;
use <?php echo $this->hydratorNamespace; ?>;
use <?php echo $this->dtoNamespace; ?>;
use <?php echo $this->daoNamespace; ?>;
use <?php echo $this->unitTestNamespace; ?>\<?php echo $this->dataObject->getNamespace(); ?>\<?php echo $this->entityName; ?>Fixture;

class RemoveTest extends \PHPUnit_Framework_TestCase
{
    public function testRemove()
    {
        FixtureManager::purge();
        $em = FixtureManager::getEm();

<?php
$keyTestable = array();
$columnCollection = $this->dataObject->getMetadata()->getColumnCollection(true);
foreach($columnCollection as $field => $metadata):
$keyToTest = null;
$modifiedValue = $this->getHelper('FixtureRenderer')->render($metadata);
?>
        $<?php echo $metadata->getName(); ?> = <?php echo $this->getHelper('FixtureRenderer')->render($metadata); ?>;
<?php endforeach; ?>

        $dto = new <?php echo $this->dataObjectName; ?>();
        $dto<?php
        $columnCollection = $this->dataObject->getMetadata()->getColumnCollection(true);
        foreach($columnCollection as $field => $metadata):
if(null === $keyToTest) {
    $keyToTest = $metadata->getName();
}
?>
           ->set<?php echo $metadata->getName(true); ?>($<?php echo $metadata->getName(); ?>)<?php if($metadata == end($columnCollection)): ?>;<?php endif; ?><?php echo "\n"; ?>
<?php endforeach; ?>

        $sUT = new <?php echo $this->entityName; ?>DAO($em, new <?php echo $this->entityName; ?>Hydrator());
        $dtoPersisted = $sUT->persist($dto);

        $sUT->remove($dtoPersisted);

        $this->setExpectedException('<?php echo $this->exceptionNamespace; ?>');
        $sUT->find($dtoPersisted);
    }

    public function testRemoveFailed()
    {
        FixtureManager::purge();
        $em = FixtureManager::getEm();

        $sUT = new <?php echo $this->daoName; ?>($em, new <?php echo $this->hydratorName; ?>());

        $dto = new <?php echo $this->dataObjectName; ?>();

        $this->setExpectedException('<?php echo $this->exceptionNamespace; ?>');
        $sUT->remove($dto);
    }
}

