    public function newAction()
    {
        $formBuilder = <?php echo $this->entity_class; ?>FormBuilderFactory::getInstance();
        $dao         = DAOFactory::getInstance();
        $datas       = $this->getRequest()->getParams();

        $form = $formBuilder->getBaseForm();

        if($this->getRequest()->isPost() && $form->isValid($datas)) {
            $dataObject = $form->getDataObject();

            $dao->persist($dataObject);

            $this->_helper->getHelper('Redirector')->goToRoute("<?php echo $this->dataObject->getModulesName(); ?>-<?php echo $this->dataObject->getClassName(); ?>");
        }

        $this->view->form = $form;
    }