<?php
echo '<?php' . "\n";
?>
namespace <?php echo $this->formGenerator->getNamespace(); ?>\Form;

use <?php echo $this->dtoNamespace; ?>;
use <?php echo $this->formGenerator->getNamespace(); ?>\Form\<?php echo $this->ucFirstModelName; ?>Form;
use Zend\Stdlib\Hydrator\ClassMethods;
use Zend\Form\View\Helper\Form;
use Zend\Mvc\Router\Http\TreeRouteStack;

class Abstract<?php echo $this->ucFirstModelName; ?>Form
{
    /**
     * @var <?php echo $this->ucFirstModelName; ?>Form
     */
    private $form       = null;
    /**
     * @var ClassMethods
     */
    private $hydrator   = null;
    /**
     * @var Form
     */
    private $formHelper = null;
    /**
     * @var TreeRouteStack
     */
    private $router     = null;

    /**
     * @param <?php echo $this->ucFirstModelName; ?>Form $form
     * @param ClassMethods $hydrator
     * @param Form $formHelper
     * @param TreeRouteStack $router
     */
    public function __construct(
        <?php echo $this->ucFirstModelName; ?>Form $form,
        ClassMethods $hydrator,
        Form $formHelper,
        TreeRouteStack $router
    ) {
        $this->form       = $form;
        $this->hydrator   = $hydrator;
        $this->formHelper = $formHelper;
        $this->router     = $router;
    }

    /**
     * @param array $datas
     * @return boolean
     */
    public function isValid(array $datas)
    {
        $this->form->setData($datas);
        return $this->form->isValid();
    }

    /**
     * @return <?php echo $this->ucFirstModelName; ?>Form
     */
    public function get($value)
    {
        return $this->form->get($value);
    }

    public function prepare()
    {
        $this->form->prepare();
    }

    public function openTag()
    {
        $formHelper = $this->formHelper;
        return $formHelper->openTag($this->form);
    }

    public function closeTag()
    {
        $formHelper = $this->formHelper;
        return $formHelper->closeTag($this->form);
    }

    /**
     * @param <?php echo $this->ucFirstModelName; ?>DataObject $value
     * @return void
     */
    public function populate(<?php echo $this->ucFirstModelName; ?>DataObject $value)
    {
        $tmp = $this->hydrator->extract($value);

        return $this->form->setData($tmp);
    }

    /**
     * @param array $datas
     * @param <?php echo $this->ucFirstModelName; ?>DataObject $<?php echo $this->ucFirstModelName; ?>DTO
     */
    public function getDTO(<?php echo $this->ucFirstModelName; ?>DataObject $<?php echo $this->ucFirstModelName; ?>DTO = null)
    {
        if(null === $<?php echo $this->ucFirstModelName; ?>DTO) {
            $<?php echo $this->ucFirstModelName; ?>DTO = new <?php echo $this->ucFirstModelName; ?>DataObject();
        } else {
            $<?php echo $this->ucFirstModelName; ?>DTO = clone $<?php echo $this->ucFirstModelName; ?>DTO;
        }

        return $this->hydrator->hydrate(
            $this->form->getData(),
            $<?php echo $this->ucFirstModelName; ?>DTO
        );
    }
}
