<?php
echo '<?php' . "\n";
$lcfirstEntityName              = $this->formGenerator->getMetadata()->getName(true);

?>
namespace <?php echo $this->formGenerator->getNamespace(); ?>\DataObject;

class <?php echo $this->dataObjectName . "\n"; ?>
{
<?php
/* Traitement des champs */
foreach($this->formGenerator->getAttributeName() as $originalName => $name):

	$type = $this->formGenerator->getMetadata()->getColumn($originalName)->getType();
?>
    /**
     * @var <?php echo $type . "\n"; ?>
     */
    private $<?php echo $this->getHelper('Text')->toCamelCase($name); ?> = null;
<?php endforeach; ?>

<?php
/* Traitement des champs */
foreach($this->formGenerator->getAttributeName() as $originalName => $name):

	$type = $this->formGenerator->getMetadata()->getColumn($originalName)->getType();
?>
    /**
     * @param <?php echo $type; ?> $value
     * @return \<?php echo $this->formGenerator->getNamespace(); ?>\DataObject\<?php echo $this->dataObjectName . "\n"; ?>
     */
    public function set<?php echo $this->getHelper('Text')->toCamelCase($name, true); ?>($value)
    {
        $this-><?php echo $this->getHelper('Text')->toCamelCase($name); ?> = $value;
        return $this;
    }
<?php endforeach; ?>

<?php
/* Traitement des champs */
foreach($this->formGenerator->getAttributeName() as $originalName => $name):

	$type = $this->formGenerator->getMetadata()->getColumn($originalName)->getType();
?>
    /**
     * @return <?php echo $type . "\n"; ?>
     */
    public function get<?php echo $this->getHelper('Text')->toCamelCase($name, true); ?>()
    {
        return $this-><?php echo $this->getHelper('Text')->toCamelCase($name); ?>;
    }
<?php endforeach; ?>
}
