<?php echo '<?php' . "\n"; ?>
namespace <?php echo $this->unitTestNamespace; ?>\<?php echo $this->dataObject->getNamespace(); ?>;

use DateTime;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\FixtureInterface;
use <?php echo $this->dataObject->getEntity(); ?>;

<?php
    $length = str_repeat(' ', strlen('a' . $this->dataObject->getEntityName()));
    $loremIpsumGenerator = new \CrudGenerator\Generators\LoremIpsumGenerator();
?>
class <?php echo $this->dataObject->getEntityName(); ?>Fixture implements FixtureInterface
{
    public $entity = null;

    public function load(ObjectManager $manager)
    {
            $this->entity = new <?php echo $this->dataObject->getEntityName(); ?>();
<?php

$fixtureRender = (function($metadata) use($loremIpsumGenerator) {
    if($metadata->getType() == 'integer' || $metadata->getType() == 'float') {
        return rand(0, 50);
    } elseif($metadata->getType() == 'string') {
        return '"' . substr($loremIpsumGenerator->getContent($metadata->getLength(), 'plain'), 0, $metadata->getLength()) . '"';
    } elseif($metadata->getType() == 'date') {
        return 'new DateTime()';
    } elseif($metadata->getType() == 'bool') {
        return 'true';
    }
});

?>
        $this->entity
<?php foreach($this->dataObject->getMetadata()->getColumnCollection() as $field => $metadata): ?>
<?php
/*if(isset($metadata['id']) && $metadata['id'] == true) {
    continue;
}*/
?>
<?php if($metadata == reset($this->dataObject->getMetadata()->getColumnCollection())): ?>
                     ->set<?php echo ucfirst($metadata->getName()); ?>(<?php echo $fixtureRender($metadata); ?>)<?php echo "\n"; ?>
<?php else: ?>
                     ->set<?php echo ucfirst($metadata->getName()); ?>(<?php echo $fixtureRender($metadata); ?>)<?php if($metadata == end($this->dataObject->getMetadata()->getColumnCollection())): ?>;<?php endif; ?><?php echo "\n"; ?>
<?php endif; ?>
<?php endforeach; ?>

        $manager->persist($this->entity);
        $manager->flush();
    }
}