<?php
echo '<?php' . "\n";
$pathBackend = __DIR__ . '/../environnement/' . $this->architectGenerator->getEnvironnement('backend') . '/';
$databaseConnectorClassName     = $this->renderFile($pathBackend . 'className.phtml');
$databaseConnectionVariableName = $this->renderFile($pathBackend . 'variableName.phtml');
$typeReturnedByDatabase         = $this->renderFile($pathBackend . 'typeReturnedByDatabase.phtml');
$concreteTypeReturnedByDatabase = $this->renderFile($pathBackend . 'concreteTypeReturnedByDatabase.phtml');

?>
namespace <?php echo $this->unitTestNamespace; ?>;

use DateTime;
use <?php echo $this->renderFile($pathBackend . 'fullClass.phtml'); ?>;
use <?php echo $this->dtoNamespace; ?>;
use <?php echo $this->hydratorNamespace; ?>;
<?php echo $this->renderFile(__DIR__ . '/../environnement/' . $this->architectGenerator->getEnvironnement('framework') . '/fullClassForUnitTest.phtml'); ?>
<?php if ('doctrine2' === $this->architectGenerator->getEnvironnement('backend')): ?>
use <?php echo $this->architectGenerator->getMetadata()->getOriginalName(); ?>;
<?php endif; ?>


<?php
    $length = str_repeat(' ', strlen('a' . $this->modelName));
?>
class <?php echo $this->fixtureName . "\n"; ?>
{
    /**
     * @var <?php echo $databaseConnectorClassName . "\n"; ?>
     */
    private $<?php echo $databaseConnectionVariableName; ?> = null;
    /**
     * @var <?php echo $this->hydratorName . "\n"; ?>
     */
    private $hydrator = null;

    /**
     * @param <?php echo $this->hydratorName; ?> $hydrator
     * @param <?php echo $databaseConnectorClassName; ?> $<?php echo $databaseConnectionVariableName . "\n"; ?>
     */
    public function __construct(<?php echo $this->hydratorName; ?> $hydrator, <?php echo $databaseConnectorClassName; ?> $<?php echo $databaseConnectionVariableName; ?>)
    {
        $this->hydrator = $hydrator;
        $this-><?php echo $databaseConnectionVariableName; ?> = $<?php echo $databaseConnectionVariableName; ?>;
    }

    /**
     * Retrieve fixture
     * @return <?php echo $this->dataObjectName . "\n"; ?>
     */
    public function getFixture()
    {
        $dataObject = new <?php echo $this->dataObjectName; ?>();
        $dataObject<?php
$columnCollection = $this->architectGenerator->getMetadata()->getColumnCollection(true);
foreach($columnCollection as $field => $metadata):
if($metadata == reset($columnCollection)): ?>
->set<?php echo $this->getHelper('Text')->toCamelCase($this->architectGenerator->getAttributeName($metadata->getName()), true); ?>(<?php echo $this->getHelper('FixtureRenderer')->render($metadata); ?>)<?php if($metadata == end($columnCollection)): ?>;<?php endif; ?><?php echo "\n"; ?>
<?php else: ?>
                   ->set<?php echo $this->getHelper('Text')->toCamelCase($this->architectGenerator->getAttributeName($metadata->getName()), true); ?>(<?php echo $this->getHelper('FixtureRenderer')->render($metadata); ?>)<?php if($metadata == end($columnCollection)): ?>;<?php endif; ?><?php echo "\n"; ?>
<?php endif; ?>
<?php endforeach; ?>

        return $dataObject;
    }

    /**
     * Load Fixture in database
     * @return <?php echo $this->dataObjectName . "\n"; ?>
     */
    public function loadFixture()
    {
        $fixture = $this->getFixture();
        $result  = $this->hydrator->popoToEntity(
            $fixture,
<?php if ('doctrine2' === $this->architectGenerator->getEnvironnement('backend')): ?>
            new <?php echo $this->architectGenerator->getMetadata()->getName(); ?>()
<?php elseif ($typeReturnedByDatabase == 'array'): ?>
            array()
<?php endif; ?>
        );

        <?php echo $this->renderFile($pathBackend . 'persistQuery.phtml'); ?>

        return $this->hydrator->entityToPopo(
            $result,
            new <?php echo $this->dataObjectName . "\n"; ?>
        );
    }

    /**
     * Return database connection
     * @return <?php echo $databaseConnectorClassName . "\n"; ?>
     */
    public function getDatabaseConnection()
    {
        return $this-><?php echo $databaseConnectionVariableName; ?>;
    }

    /**
     * Purge table
     */
    public function purge()
    {
        <?php echo $this->renderFile($pathBackend . 'purgeQueryForUnitTest.phtml'); ?>
    }
}
