<?php
echo '<?php' . "\n";
$frameworkPath = __DIR__ . '/../../environnement/' . $this->architectGenerator->getEnvironnement('framework') . '/';

?>

namespace <?php echo $this->unitTestNamespace; ?>\DAOFactory;

use <?php echo $this->daoFactoryNamespace; ?>;
use <?php echo $this->daoNamespace; ?>;
<?php echo $this->renderFile($frameworkPath . 'fullClassForUnitTest.phtml'); ?>

class GetInstanceTest extends \PHPUnit_Framework_TestCase
{
    public function testReturnType()
    {
        <?php echo $this->renderFile($frameworkPath . 'createInstanceForUnitTest.phtml') . "\n"; ?>

        $this->assertInstanceOf(
            '<?php echo $this->daoNamespace; ?>',
            <?php echo $this->daoFactoryName; ?>::getInstance($serviceManager)
        );
    }
}
