<?php echo '<?php' . "\n"; ?>
namespace <?php echo $this->unitTestNamespace; ?>\<?php echo $this->dataObject->getNamespace(); ?>\Hydrator;

use ApplicationTest\FixtureManager;
use <?php echo $this->hydratorNamespace; ?>;
use <?php echo $this->dtoNamespace; ?>;
use <?php echo $this->daoNamespace; ?>;
use <?php echo $this->unitTestNamespace; ?>\<?php echo $this->dataObject->getNamespace(); ?>\<?php echo $this->dataObject->getEntityName(); ?>Fixture;

class PopoToArrayTest extends \PHPUnit_Framework_TestCase
{
    public function testpopoToArray()
    {
<?php
$keyTestable = array();
$columnCollection = $this->dataObject->getMetadata()->getColumnCollection(true);
foreach($columnCollection as $field => $metadata):
$keyToTest = null;
$modifiedValue =$this->getHelper('FixtureRenderer')->render($metadata);
?>
        $<?php echo $metadata->getName(); ?> = <?php echo $this->getHelper('FixtureRenderer')->render($metadata); ?>;
<?php endforeach; ?>

        $dto = new <?php echo $this->dataObjectName; ?>();
        $dto<?php
        $columnCollection = $this->dataObject->getMetadata()->getColumnCollection(true);
        foreach($columnCollection as $field => $metadata):
if(null === $keyToTest) {
    $keyToTest = $metadata->getName();
}
?>
           ->set<?php echo $metadata->getName(true); ?>($<?php echo $metadata->getName(); ?>)<?php if($metadata == end($columnCollection)): ?>;<?php endif; ?><?php echo "\n"; ?>
<?php endforeach; ?>

        $sUT = new <?php echo $this->hydratorName; ?>();
        $arrayDto = $sUT->popoToArray($dto, array());

<?php
$columnCollection = $this->dataObject->getMetadata()->getColumnCollection(true);
foreach($columnCollection as $field => $metadata):
?>
        $this->assertEquals($<?php echo $metadata->getName(); ?>, $arrayDto['<?php echo $metadata->getName(); ?>']);
<?php endforeach; ?>
    }
}

